namespace Consysto.BookPreview;

/// <summary>Readable names for the genre codes used in FictionBook files; unknown codes are shown as written.</summary>
internal static class Fb2Genres
{
    private static readonly Dictionary<string, string> Names = new(StringComparer.OrdinalIgnoreCase)
    {
        ["sf"] = "Научная фантастика",
        ["sf_etc"] = "Фантастика",
        ["sf_history"] = "Альтернативная история",
        ["sf_action"] = "Боевая фантастика",
        ["sf_epic"] = "Эпическая фантастика",
        ["sf_heroic"] = "Героическая фантастика",
        ["sf_detective"] = "Детективная фантастика",
        ["sf_cyberpunk"] = "Киберпанк",
        ["sf_space"] = "Космическая фантастика",
        ["sf_social"] = "Социально-психологическая фантастика",
        ["sf_horror"] = "Ужасы",
        ["sf_humor"] = "Юмористическая фантастика",
        ["sf_fantasy"] = "Фэнтези",
        ["sf_fantasy_city"] = "Городское фэнтези",
        ["city_fantasy"] = "Городское фэнтези",
        ["fantasy_fight"] = "Боевое фэнтези",
        ["sf_postapocalyptic"] = "Постапокалипсис",
        ["sf_mystic"] = "Мистика",
        ["sf_stimpank"] = "Стимпанк",
        ["sf_technofantasy"] = "Технофэнтези",
        ["popadancy"] = "Попаданцы",
        ["litrpg"] = "ЛитРПГ",
        ["hronoopera"] = "Хроноопера",
        ["det_classic"] = "Классический детектив",
        ["det_police"] = "Полицейский детектив",
        ["det_action"] = "Боевик",
        ["det_irony"] = "Иронический детектив",
        ["det_history"] = "Исторический детектив",
        ["det_espionage"] = "Шпионский детектив",
        ["det_crime"] = "Криминальный детектив",
        ["det_political"] = "Политический детектив",
        ["det_maniac"] = "Маньяки",
        ["det_hard"] = "Крутой детектив",
        ["detective"] = "Детектив",
        ["thriller"] = "Триллер",
        ["prose_classic"] = "Классическая проза",
        ["prose_history"] = "Историческая проза",
        ["prose_contemporary"] = "Современная проза",
        ["prose_counter"] = "Контркультура",
        ["prose_rus_classic"] = "Русская классическая проза",
        ["prose_su_classics"] = "Советская классическая проза",
        ["prose_military"] = "Военная проза",
        ["prose_magic"] = "Магический реализм",
        ["prose"] = "Проза",
        ["love_contemporary"] = "Современный любовный роман",
        ["love_history"] = "Исторический любовный роман",
        ["love_detective"] = "Остросюжетный любовный роман",
        ["love_short"] = "Короткий любовный роман",
        ["love_sf"] = "Любовная фантастика",
        ["love_erotica"] = "Эротика",
        ["love"] = "Любовный роман",
        ["adv_western"] = "Вестерн",
        ["adv_history"] = "Исторические приключения",
        ["adv_indian"] = "Приключения про индейцев",
        ["adv_maritime"] = "Морские приключения",
        ["adv_geo"] = "Путешествия и география",
        ["adv_animal"] = "Природа и животные",
        ["adventure"] = "Приключения",
        ["child_tale"] = "Сказки",
        ["child_verse"] = "Детские стихи",
        ["child_prose"] = "Детская проза",
        ["child_sf"] = "Детская фантастика",
        ["child_det"] = "Детские остросюжетные",
        ["child_adv"] = "Детские приключения",
        ["child_education"] = "Детская образовательная литература",
        ["children"] = "Детская литература",
        ["poetry"] = "Поэзия",
        ["dramaturgy"] = "Драматургия",
        ["antique_ant"] = "Античная литература",
        ["antique_european"] = "Европейская старинная литература",
        ["antique_russian"] = "Древнерусская литература",
        ["antique_east"] = "Древневосточная литература",
        ["antique_myths"] = "Мифы, легенды, эпос",
        ["antique"] = "Старинная литература",
        ["sci_history"] = "История",
        ["sci_psychology"] = "Психология",
        ["sci_culture"] = "Культурология",
        ["sci_religion"] = "Религиоведение",
        ["sci_philosophy"] = "Философия",
        ["sci_politics"] = "Политика",
        ["sci_business"] = "Деловая литература",
        ["sci_economy"] = "Экономика",
        ["sci_juris"] = "Юриспруденция",
        ["sci_linguistic"] = "Языкознание",
        ["sci_medicine"] = "Медицина",
        ["sci_phys"] = "Физика",
        ["sci_math"] = "Математика",
        ["sci_chem"] = "Химия",
        ["sci_biology"] = "Биология",
        ["sci_tech"] = "Технические науки",
        ["sci_popular"] = "Научно-популярная литература",
        ["science"] = "Научная литература",
        ["comp_www"] = "Интернет",
        ["comp_programming"] = "Программирование",
        ["comp_hard"] = "Компьютерное железо",
        ["comp_soft"] = "Программы",
        ["comp_db"] = "Базы данных",
        ["comp_osnet"] = "Операционные системы и сети",
        ["computers"] = "Компьютеры",
        ["ref_encyc"] = "Энциклопедии",
        ["ref_dict"] = "Словари",
        ["ref_ref"] = "Справочники",
        ["ref_guide"] = "Руководства",
        ["reference"] = "Справочная литература",
        ["nonf_biography"] = "Биографии и мемуары",
        ["nonf_publicism"] = "Публицистика",
        ["nonf_criticism"] = "Критика",
        ["nonf_military"] = "Военная документалистика",
        ["nonfiction"] = "Документальная литература",
        ["design"] = "Искусство и дизайн",
        ["religion_rel"] = "Религия",
        ["religion_esoterics"] = "Эзотерика",
        ["religion_self"] = "Самосовершенствование",
        ["religion"] = "Религия и духовность",
        ["humor_anecdote"] = "Анекдоты",
        ["humor_prose"] = "Юмористическая проза",
        ["humor_verse"] = "Юмористические стихи",
        ["humor"] = "Юмор",
        ["home_cooking"] = "Кулинария",
        ["home_pets"] = "Домашние животные",
        ["home_crafts"] = "Хобби и ремёсла",
        ["home_entertain"] = "Развлечения",
        ["home_health"] = "Здоровье",
        ["home_garden"] = "Сад и огород",
        ["home_diy"] = "Сделай сам",
        ["home_sport"] = "Спорт",
        ["home"] = "Дом и семья",
        ["military_weapon"] = "Военная техника и оружие",
        ["military_history"] = "Военная история",
        ["foreign_sf"] = "Зарубежная фантастика",
        ["foreign_fantasy"] = "Зарубежное фэнтези",
        ["foreign_detective"] = "Зарубежный детектив",
        ["foreign_action"] = "Зарубежный боевик",
        ["foreign_prose"] = "Зарубежная проза",
        ["foreign_contemporary"] = "Современная зарубежная проза",
        ["foreign_love"] = "Зарубежный любовный роман",
        ["foreign_adventure"] = "Зарубежные приключения",
        ["foreign_children"] = "Зарубежная детская литература",
        ["foreign_poetry"] = "Зарубежная поэзия",
        ["foreign_dramaturgy"] = "Зарубежная драматургия",
        ["foreign_publicism"] = "Зарубежная публицистика",
        ["foreign_edu"] = "Зарубежная образовательная литература",
        ["foreign_antique"] = "Зарубежная старинная литература",
        ["foreign_humor"] = "Зарубежный юмор",
        ["foreign_other"] = "Зарубежное",
    };

    public static string? Describe(string? code)
    {
        var text = TextCleanup.Clean(code);
        if (text is null)
            return null;

        return Names.TryGetValue(text, out var name) ? name : text;
    }
}
